{% set name = "torchrecurrent" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchrecurrent-{{ version }}.tar.gz
  sha256: f50d3d19800a47ee8f105d899776c62c56b6bc5ca02a4bd3fd812f04ca62b98e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - torchrecurrent
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MartinuzziFrancesco/torchrecurrent
  summary: A package for recurrent neural networks in PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MartinuzziFrancesco
